### ISSUE TITLE
The parameter `tumblr_id` should be a string.

### ISSUE THREAD

**Issue by metadiv** [bfred-it/tumblr-upload#2]
Keep getting this error.

```
TypeError: The parameter `tumblr_id` should be a string.
    at uploadWithIniConfig (/Users/MikeDove/Sites/localhost/12-strong-tumblr/node_modules/tumblr-upload/index.js:119:9)
    at Gulp.<anonymous> (/Users/MikeDove/Sites/localhost/12-strong-tumblr/gulpfile.js:140:2)
    at module.exports (/Users/MikeDove/Sites/localhost/12-strong-tumblr/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/MikeDove/Sites/localhost/12-strong-tumblr/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/MikeDove/Sites/localhost/12-strong-tumblr/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/MikeDove/Sites/localhost/12-strong-tumblr/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
```

here is my code. (other strings changed for secuuirty)

```js
var tumblrUpload = require("tumblr-upload"),
  fs = require("fs"),
  template = fs.readFileSync("dist/index.tumblr.html", "utf8"),
  production = new tumblrUpload.Blog({
    tumblr_id: "dev12s",
    user_form_key: "xxxxx",
    anon_id: "xxxx",
    pfe: "0000",
    pfp: "xxxx",
    pfs: "xxxx",
    pfu: "0000"
  });

gulp.task("tumblerTemplate", function() {
  tumblrUpload(template, function(err) {
    if (err) {
      console.error(err);
      return;
    }
    console.log("Uploaded!");
  });
});
```

**Comment by fregante** [comment]
In your task, if you call `tumblrUpload` directly it tries to use the `.ini` configuration. Instead, you need to call `production.upload()`

**Comment by metadiv** [comment]
Thank you, fixed.
